title: Awad Al
author: Awad Al
email: your.email@example.com
description: >-
  Professional portfolio and resume.
theme: minima
header_pages:
  - resume.md
github_username: Awad-Al
linkedin_username: your-linkedin-handle
