title: Awad AlNasrallah
author: Awad AlNasrallah
email: awad.alnasrallah@gmail.com
description: >-
  Personal website.
theme: minima
header_pages:
  - resume.md
  - projects.md
github_username: Awad-Al
linkedin_username: awad-alnasrallah-64367221a
